#pragma once

#include "Core/Container/String.h"
#include "Core/Container/Vector.h"

extern "C" 
{
    #include "unibilium.h"
}

namespace UI 
{
    enum class SequenceBoolean 
    {
        AutoLeftMargin         = unibi_auto_left_margin,
        AutoRightMargin        = unibi_auto_right_margin,
        NoEscCtlc              = unibi_no_esc_ctlc,
        CeolStandoutGlitch     = unibi_ceol_standout_glitch,
        EatNewlineGlitch       = unibi_eat_newline_glitch,
        EraseOverstrike        = unibi_erase_overstrike,
        GenericType            = unibi_generic_type,
        HardCopy               = unibi_hard_copy,
        HasMetaKey             = unibi_has_meta_key,
        HasStatusLine          = unibi_has_status_line,
        InsertNullGlitch       = unibi_insert_null_glitch,
        MemoryAbove            = unibi_memory_above,
        MemoryBelow            = unibi_memory_below,
        MoveInsertMode         = unibi_move_insert_mode,
        MoveStandoutMode       = unibi_move_standout_mode,
        OverStrike             = unibi_over_strike,
        StatusLineEscOK        = unibi_status_line_esc_ok,
        DestTabsMagicSmso      = unibi_dest_tabs_magic_smso,
        TildeGlitch            = unibi_tilde_glitch,
        TransparentUnderline   = unibi_transparent_underline,
        XOnXOff                = unibi_xon_xoff,
        NeedsXOnXOff           = unibi_needs_xon_xoff,
        PrtrSilent             = unibi_prtr_silent,
        HardCursor             = unibi_hard_cursor,
        NonRevRmcup            = unibi_non_rev_rmcup,
        NoPadChar              = unibi_no_pad_char,
        NonDestScrollRegion    = unibi_non_dest_scroll_region,
        Can_change             = unibi_can_change,
        BackColorErase         = unibi_back_color_erase,
        HueLightnessSaturation = unibi_hue_lightness_saturation,
        ColAddrGlitch          = unibi_col_addr_glitch,
        CrCancelsMicroMode     = unibi_cr_cancels_micro_mode,
        HasPrintWheel          = unibi_has_print_wheel,
        RowAddrGlitch          = unibi_row_addr_glitch,
        SemiAutoRightMargin    = unibi_semi_auto_right_margin,
        CpiChangesRes          = unibi_cpi_changes_res,
        LpiChangesRes          = unibi_lpi_changes_res,
        BackspacesWithBs       = unibi_backspaces_with_bs,
        CrtNoScrolling         = unibi_crt_no_scrolling,
        NoCorrectlyWorkingCR   = unibi_no_correctly_working_cr,
        GnuHasMetaKey          = unibi_gnu_has_meta_key,
        LinefeedIsNewline      = unibi_linefeed_is_newline,
        HasHardwareTabs        = unibi_has_hardware_tabs,
        ReturnDoesClrEol       = unibi_return_does_clr_eol,
    };

    enum class SequenceInteger 
    {
        Columns              = unibi_columns,
        InitTabs             = unibi_init_tabs,
        Lines                = unibi_lines,
        LinesOfMemory        = unibi_lines_of_memory,
        MagicCookieGlitch    = unibi_magic_cookie_glitch,
        PaddingBaudRate      = unibi_padding_baud_rate,
        VirtualTerminal      = unibi_virtual_terminal,
        WidthStatusLine      = unibi_width_status_line,
        NumLabels            = unibi_num_labels,
        LabelHeight          = unibi_label_height,
        LabelWidth           = unibi_label_width,
        MaxAttributes        = unibi_max_attributes,
        MaximumWindows       = unibi_maximum_windows,
        MaxColors            = unibi_max_colors,
        MaxPairs             = unibi_max_pairs,
        NoColorVideo         = unibi_no_color_video,
        BufferCapacity       = unibi_buffer_capacity,
        DotVertSpacing       = unibi_dot_vert_spacing,
        DotHorzSpacing       = unibi_dot_horz_spacing,
        MaxMicroAddress      = unibi_max_micro_address,
        MaxMicroJump         = unibi_max_micro_jump,
        MicroColSize         = unibi_micro_col_size,
        MicroLineSize        = unibi_micro_line_size,
        NumberOfPins         = unibi_number_of_pins,
        OutputResChar        = unibi_output_res_char,
        OutputResLine        = unibi_output_res_line,
        OutputResHorzInch    = unibi_output_res_horz_inch,
        OutputResVertInch    = unibi_output_res_vert_inch,
        PrintRate            = unibi_print_rate,
        WideCharSize         = unibi_wide_char_size,
        Buttons              = unibi_buttons,
        BitImageEntwining    = unibi_bit_image_entwining,
        BitImageType         = unibi_bit_image_type,
        MagicCookieGlitchUL  = unibi_magic_cookie_glitch_ul,
        CarriageReturnDelay  = unibi_carriage_return_delay,
        NewlineDelay         = unibi_new_line_delay,
        BackspaceDelay       = unibi_backspace_delay,
        HorizontalTabDelay   = unibi_horizontal_tab_delay,
        NumberOfFunctionKeys = unibi_number_of_function_keys,
    };

    enum class SequenceString 
    {
        BackTab                = unibi_back_tab,
        Bell                   = unibi_bell,
        CarriageReturn         = unibi_carriage_return,
        ChangeScrollRegion     = unibi_change_scroll_region,
        ClearAllTabs           = unibi_clear_all_tabs,
        ClearScreen            = unibi_clear_screen,
        ClrEol                 = unibi_clr_eol,
        ClrEos                 = unibi_clr_eos,
        ColumnAddress          = unibi_column_address,
        CommandCharacter       = unibi_command_character,
        CursorAddress          = unibi_cursor_address,
        CursorDown             = unibi_cursor_down,
        CursorHome             = unibi_cursor_home,
        CursorInvisible        = unibi_cursor_invisible,
        CursorLeft             = unibi_cursor_left,
        CursorMemAddress       = unibi_cursor_mem_address,
        CursorNormal           = unibi_cursor_normal,
        CursorRight            = unibi_cursor_right,
        CursorToLL             = unibi_cursor_to_ll,
        CursorUp               = unibi_cursor_up,
        CursorVisible          = unibi_cursor_visible,
        DeleteCharacter        = unibi_delete_character,
        DeleteLine             = unibi_delete_line,
        DisStatusLine          = unibi_dis_status_line,
        DownHalfLine           = unibi_down_half_line,
        EnterAltCharsetMode    = unibi_enter_alt_charset_mode,
        EnterBlinkMode         = unibi_enter_blink_mode,
        EnterBoldMode          = unibi_enter_bold_mode,
        EnterCAMode            = unibi_enter_ca_mode,
        EnterDeleteMode        = unibi_enter_delete_mode,
        EnterDimMode           = unibi_enter_dim_mode,
        EnterInsertMode        = unibi_enter_insert_mode,
        EnterSecureMode        = unibi_enter_secure_mode,
        EnterProtectedMode     = unibi_enter_protected_mode,
        EnterReverseMode       = unibi_enter_reverse_mode,
        EnterStandoutMode      = unibi_enter_standout_mode,
        EnterUnderlineMode     = unibi_enter_underline_mode,
        EraseChars             = unibi_erase_chars,
        ExitAltCharsetMode     = unibi_exit_alt_charset_mode,
        ExitAttributeMode      = unibi_exit_attribute_mode,
        ExitCAMode             = unibi_exit_ca_mode,
        ExitDeleteMode         = unibi_exit_delete_mode,
        ExitInsertMode         = unibi_exit_insert_mode,
        ExitStandoutMode       = unibi_exit_standout_mode,
        ExitUnderlineMode      = unibi_exit_underline_mode,
        FlashScreen            = unibi_flash_screen,
        FormFeed               = unibi_form_feed,
        FromStatusLine         = unibi_from_status_line,
        Init1String            = unibi_init_1string,
        Init2String            = unibi_init_2string,
        Init3String            = unibi_init_3string,
        InitFile               = unibi_init_file,
        InsertCharacter        = unibi_insert_character,
        InsertLine             = unibi_insert_line,
        InsertPadding          = unibi_insert_padding,
        KeyBackspace           = unibi_key_backspace,
        KeyCATab               = unibi_key_catab,
        KeyClear               = unibi_key_clear,
        KeyCTab                = unibi_key_ctab,
        KeyDC                  = unibi_key_dc,
        KeyDL                  = unibi_key_dl,
        KeyDown                = unibi_key_down,
        KeyEIC                 = unibi_key_eic,
        KeyEOL                 = unibi_key_eol,
        KeyEos                 = unibi_key_eos,
        KeyF0                  = unibi_key_f0,
        KeyF1                  = unibi_key_f1,
        KeyF10                 = unibi_key_f10,
        KeyF2                  = unibi_key_f2,
        KeyF3                  = unibi_key_f3,
        KeyF4                  = unibi_key_f4,
        KeyF5                  = unibi_key_f5,
        KeyF6                  = unibi_key_f6,
        KeyF7                  = unibi_key_f7,
        KeyF8                  = unibi_key_f8,
        KeyF9                  = unibi_key_f9,
        KeyHome                = unibi_key_home,
        KeyIC                  = unibi_key_ic,
        KeyIL                  = unibi_key_il,
        KeyLeft                = unibi_key_left,
        KeyLL                  = unibi_key_ll,
        KeyNpage               = unibi_key_npage,
        KeyPpage               = unibi_key_ppage,
        KeyRight               = unibi_key_right,
        KeySF                  = unibi_key_sf,
        KeySR                  = unibi_key_sr,
        KeySTab                = unibi_key_stab,
        KeyUp                  = unibi_key_up,
        KeypadLocal            = unibi_keypad_local,
        KeypadXmit             = unibi_keypad_xmit,
        LabF0                  = unibi_lab_f0,
        LabF1                  = unibi_lab_f1,
        LabF10                 = unibi_lab_f10,
        LabF2                  = unibi_lab_f2,
        LabF3                  = unibi_lab_f3,
        LabF4                  = unibi_lab_f4,
        LabF5                  = unibi_lab_f5,
        LabF6                  = unibi_lab_f6,
        LabF7                  = unibi_lab_f7,
        LabF8                  = unibi_lab_f8,
        LabF9                  = unibi_lab_f9,
        MetaOff                = unibi_meta_off,
        MetaOn                 = unibi_meta_on,
        Newline                = unibi_newline,
        PadChar                = unibi_pad_char,
        ParmDCh                = unibi_parm_dch,
        ParmDeleteLine         = unibi_parm_delete_line,
        ParmDownCursor         = unibi_parm_down_cursor,
        ParmICh                = unibi_parm_ich,
        ParmIndex              = unibi_parm_index,
        ParmInsertLine         = unibi_parm_insert_line,
        ParmLeftCursor         = unibi_parm_left_cursor,
        ParmRightCursor        = unibi_parm_right_cursor,
        ParmRIndex             = unibi_parm_rindex,
        ParmUpCursor           = unibi_parm_up_cursor,
        PkeyKey                = unibi_pkey_key,
        PkeyLocal              = unibi_pkey_local,
        PkeyXmit               = unibi_pkey_xmit,
        PrintScreen            = unibi_print_screen,
        PrtrOff                = unibi_prtr_off,
        PrtrOn                 = unibi_prtr_on,
        RepeatChar             = unibi_repeat_char,
        Reset1String           = unibi_reset_1string,
        Reset2String           = unibi_reset_2string,
        Reset3String           = unibi_reset_3string,
        ResetFile              = unibi_reset_file,
        RestoreCursor          = unibi_restore_cursor,
        RowAddress             = unibi_row_address,
        SaveCursor             = unibi_save_cursor,
        ScrollForward          = unibi_scroll_forward,
        ScrollReverse          = unibi_scroll_reverse,
        SetAttributes          = unibi_set_attributes,
        SetTab                 = unibi_set_tab,
        SetWindow              = unibi_set_window,
        Tab                    = unibi_tab,
        ToStatusLine           = unibi_to_status_line,
        UnderlineChar          = unibi_underline_char,
        UpHalfLine             = unibi_up_half_line,
        InitProg               = unibi_init_prog,
        KeyA1                  = unibi_key_a1,
        KeyA3                  = unibi_key_a3,
        KeyB2                  = unibi_key_b2,
        KeyC1                  = unibi_key_c1,
        KeyC3                  = unibi_key_c3,
        PrtrNon                = unibi_prtr_non,
        CharPadding            = unibi_char_padding,
        AcsChars               = unibi_acs_chars,
        PlabNorm               = unibi_plab_norm,
        KeyBtab                = unibi_key_btab,
        EnterXOnMode           = unibi_enter_xon_mode,
        ExitXOnMode            = unibi_exit_xon_mode,
        EnterAmMode            = unibi_enter_am_mode,
        ExitAmMode             = unibi_exit_am_mode,
        XOnCharacter           = unibi_xon_character,
        XOffCharacter          = unibi_xoff_character,
        EnaAcs                 = unibi_ena_acs,
        LabelOon               = unibi_label_on,
        LabelOff               = unibi_label_off,
        KeyBeg                 = unibi_key_beg,
        KeyCancel              = unibi_key_cancel,
        KeyClose               = unibi_key_close,
        KeyCommand             = unibi_key_command,
        KeyCopy                = unibi_key_copy,
        KeyCreate              = unibi_key_create,
        KeyEnd                 = unibi_key_end,
        KeyEnter               = unibi_key_enter,
        KeyExit                = unibi_key_exit,
        KeyFind                = unibi_key_find,
        KeyHelp                = unibi_key_help,
        KeyMark                = unibi_key_mark,
        KeyMessage             = unibi_key_message,
        KeyMove                = unibi_key_move,
        KeyNext                = unibi_key_next,
        KeyOpen                = unibi_key_open,
        KeyOptions             = unibi_key_options,
        KeyPrevious            = unibi_key_previous,
        KeyPrint               = unibi_key_print,
        KeyRedo                = unibi_key_redo,
        KeyReference           = unibi_key_reference,
        KeyRefresh             = unibi_key_refresh,
        KeyReplace             = unibi_key_replace,
        KeyRestart             = unibi_key_restart,
        KeyResume              = unibi_key_resume,
        KeySave                = unibi_key_save,
        KeySuspend             = unibi_key_suspend,
        KeyUndo                = unibi_key_undo,
        KeySBeg                = unibi_key_sbeg,
        KeySCancel             = unibi_key_scancel,
        KeySCommand            = unibi_key_scommand,
        KeySCopy               = unibi_key_scopy,
        KeySCreate             = unibi_key_screate,
        KeySDC                 = unibi_key_sdc,
        KeySDL                 = unibi_key_sdl,
        KeySelect              = unibi_key_select,
        KeySEnd                = unibi_key_send,
        KeySEOL                = unibi_key_seol,
        KeySExit               = unibi_key_sexit,
        KeySFind               = unibi_key_sfind,
        KeySHelp               = unibi_key_shelp,
        KeySHome               = unibi_key_shome,
        KeySIC                 = unibi_key_sic,
        KeySLeft               = unibi_key_sleft,
        KeySMessage            = unibi_key_smessage,
        KeySMove               = unibi_key_smove,
        KeySNext               = unibi_key_snext,
        KeySOptions            = unibi_key_soptions,
        KeySPrevious           = unibi_key_sprevious,
        KeySPrint              = unibi_key_sprint,
        KeySRedo               = unibi_key_sredo,
        KeySReplace            = unibi_key_sreplace,
        KeySRight              = unibi_key_sright,
        KeySRsume              = unibi_key_srsume,
        KeySSave               = unibi_key_ssave,
        KeySSuspend            = unibi_key_ssuspend,
        KeySUndo               = unibi_key_sundo,
        ReqForInput            = unibi_req_for_input,
        KeyF11                 = unibi_key_f11,
        KeyF12                 = unibi_key_f12,
        KeyF13                 = unibi_key_f13,
        KeyF14                 = unibi_key_f14,
        KeyF15                 = unibi_key_f15,
        KeyF16                 = unibi_key_f16,
        KeyF17                 = unibi_key_f17,
        KeyF18                 = unibi_key_f18,
        KeyF19                 = unibi_key_f19,
        KeyF20                 = unibi_key_f20,
        KeyF21                 = unibi_key_f21,
        KeyF22                 = unibi_key_f22,
        KeyF23                 = unibi_key_f23,
        KeyF24                 = unibi_key_f24,
        KeyF25                 = unibi_key_f25,
        KeyF26                 = unibi_key_f26,
        KeyF27                 = unibi_key_f27,
        KeyF28                 = unibi_key_f28,
        KeyF29                 = unibi_key_f29,
        KeyF30                 = unibi_key_f30,
        KeyF31                 = unibi_key_f31,
        KeyF32                 = unibi_key_f32,
        KeyF33                 = unibi_key_f33,
        KeyF34                 = unibi_key_f34,
        KeyF35                 = unibi_key_f35,
        KeyF36                 = unibi_key_f36,
        KeyF37                 = unibi_key_f37,
        KeyF38                 = unibi_key_f38,
        KeyF39                 = unibi_key_f39,
        KeyF40                 = unibi_key_f40,
        KeyF41                 = unibi_key_f41,
        KeyF42                 = unibi_key_f42,
        KeyF43                 = unibi_key_f43,
        KeyF44                 = unibi_key_f44,
        KeyF45                 = unibi_key_f45,
        KeyF46                 = unibi_key_f46,
        KeyF47                 = unibi_key_f47,
        KeyF48                 = unibi_key_f48,
        KeyF49                 = unibi_key_f49,
        KeyF50                 = unibi_key_f50,
        KeyF51                 = unibi_key_f51,
        KeyF52                 = unibi_key_f52,
        KeyF53                 = unibi_key_f53,
        KeyF54                 = unibi_key_f54,
        KeyF55                 = unibi_key_f55,
        KeyF56                 = unibi_key_f56,
        KeyF57                 = unibi_key_f57,
        KeyF58                 = unibi_key_f58,
        KeyF59                 = unibi_key_f59,
        KeyF60                 = unibi_key_f60,
        KeyF61                 = unibi_key_f61,
        KeyF62                 = unibi_key_f62,
        KeyF63                 = unibi_key_f63,
        ClrBOL                 = unibi_clr_bol,
        ClearMargins           = unibi_clear_margins,
        SetLeftMargin          = unibi_set_left_margin,
        SetRightMargin         = unibi_set_right_margin,
        LabelFormat            = unibi_label_format,
        SetClock               = unibi_set_clock,
        DisplayClock           = unibi_display_clock,
        RemoveClock            = unibi_remove_clock,
        CreateWindow           = unibi_create_window,
        GotoWindow             = unibi_goto_window,
        Hangup                 = unibi_hangup,
        DialPhone              = unibi_dial_phone,
        QuickDial              = unibi_quick_dial,
        Tone                   = unibi_tone,
        Pulse                  = unibi_pulse,
        FlashHook              = unibi_flash_hook,
        FixedPause             = unibi_fixed_pause,
        WaitTone               = unibi_wait_tone,
        User0                  = unibi_user0,
        User1                  = unibi_user1,
        User2                  = unibi_user2,
        User3                  = unibi_user3,
        User4                  = unibi_user4,
        User5                  = unibi_user5,
        User6                  = unibi_user6,
        User7                  = unibi_user7,
        User8                  = unibi_user8,
        User9                  = unibi_user9,
        OrigPair               = unibi_orig_pair,
        OrigColors             = unibi_orig_colors,
        InitializeColor        = unibi_initialize_color,
        InitializePair         = unibi_initialize_pair,
        SetColorPair           = unibi_set_color_pair,
        SetForeground          = unibi_set_foreground,
        SetBackground          = unibi_set_background,
        ChangeCharPitch        = unibi_change_char_pitch,
        ChangeLinePitch        = unibi_change_line_pitch,
        ChangeResHorz          = unibi_change_res_horz,
        ChangeResVert          = unibi_change_res_vert,
        DefineChar             = unibi_define_char,
        EnterDoublewideMode    = unibi_enter_doublewide_mode,
        EnterDraftQuality      = unibi_enter_draft_quality,
        EnterItalicsMode       = unibi_enter_italics_mode,
        EnterLeftwardMode      = unibi_enter_leftward_mode,
        EnterMicroMode         = unibi_enter_micro_mode,
        EnterNearLetterQuality = unibi_enter_near_letter_quality,
        EnterNormalQuality     = unibi_enter_normal_quality,
        EnterShadowMode        = unibi_enter_shadow_mode,
        EnterSubscriptMode     = unibi_enter_subscript_mode,
        EnterSuperscriptMode   = unibi_enter_superscript_mode,
        EnterUpwardMode        = unibi_enter_upward_mode,
        ExitDoublewideMode     = unibi_exit_doublewide_mode,
        ExitItalicsMode        = unibi_exit_italics_mode,
        ExitLeftwardMode       = unibi_exit_leftward_mode,
        ExitMicroMode          = unibi_exit_micro_mode,
        ExitShadowMode         = unibi_exit_shadow_mode,
        ExitSubscriptMode      = unibi_exit_subscript_mode,
        ExitSuperscriptMode    = unibi_exit_superscript_mode,
        ExitUpwardMode         = unibi_exit_upward_mode,
        MicroColumnAddress     = unibi_micro_column_address,
        MicroDown              = unibi_micro_down,
        MicroLeft              = unibi_micro_left,
        MicroRight             = unibi_micro_right,
        MicroRowAddress        = unibi_micro_row_address,
        MicroUp                = unibi_micro_up,
        OrderOfPins            = unibi_order_of_pins,
        ParmDownMicro          = unibi_parm_down_micro,
        ParmLeftMicro          = unibi_parm_left_micro,
        ParmRightMicro         = unibi_parm_right_micro,
        ParmUpMicro            = unibi_parm_up_micro,
        SelectCharSet          = unibi_select_char_set,
        SetBottomMargin        = unibi_set_bottom_margin,
        SetBottomMarginParm    = unibi_set_bottom_margin_parm,
        SetLeftMarginParm      = unibi_set_left_margin_parm,
        SetRightMarginParm     = unibi_set_right_margin_parm,
        SetTopMargin           = unibi_set_top_margin,
        SetTopMarginParm       = unibi_set_top_margin_parm,
        StartBitImage          = unibi_start_bit_image,
        StartCharSetDef        = unibi_start_char_set_def,
        StopBitImage           = unibi_stop_bit_image,
        StopCharSetDef         = unibi_stop_char_set_def,
        SubscriptCharacters    = unibi_subscript_characters,
        SuperscriptCharacters  = unibi_superscript_characters,
        TheseCauseCR           = unibi_these_cause_cr,
        ZeroMotion             = unibi_zero_motion,
        CharSetNames           = unibi_char_set_names,
        KeyMouse               = unibi_key_mouse,
        MouseInfo              = unibi_mouse_info,
        ReqMousePos            = unibi_req_mouse_pos,
        GetMouse               = unibi_get_mouse,
        SetAForeground         = unibi_set_a_foreground,
        SetABackground         = unibi_set_a_background,
        PkeyPlab               = unibi_pkey_plab,
        DeviceType             = unibi_device_type,
        CodeSetInit            = unibi_code_set_init,
        Set0DesSeq             = unibi_set0_des_seq,
        Set1DesSeq             = unibi_set1_des_seq,
        Set2DesSeq             = unibi_set2_des_seq,
        Set3DesSeq             = unibi_set3_des_seq,
        SetLRMargin            = unibi_set_lr_margin,
        SetTBMargin            = unibi_set_tb_margin,
        BitImageRepeat         = unibi_bit_image_repeat,
        BitImageNewline        = unibi_bit_image_newline,
        BitImageCarriageReturn = unibi_bit_image_carriage_return,
        ColorNames             = unibi_color_names,
        DefineBitImageRegion   = unibi_define_bit_image_region,
        EndBitImageRegion      = unibi_end_bit_image_region,
        SetColorBand           = unibi_set_color_band,
        SetPageLength          = unibi_set_page_length,
        DisplayPcChar          = unibi_display_pc_char,
        EnterPcCharsetMode     = unibi_enter_pc_charset_mode,
        ExitPcCharsetMode      = unibi_exit_pc_charset_mode,
        EnterScancodeMode      = unibi_enter_scancode_mode,
        ExitScancodeMode       = unibi_exit_scancode_mode,
        PcTermOptions          = unibi_pc_term_options,
        ScancodeEscape         = unibi_scancode_escape,
        AltScancodeEsc         = unibi_alt_scancode_esc,
        EnterHorizontalHlMode  = unibi_enter_horizontal_hl_mode,
        EnterLeftHlMode        = unibi_enter_left_hl_mode,
        EnterLowHlMode         = unibi_enter_low_hl_mode,
        EnterRightHlMode       = unibi_enter_right_hl_mode,
        EnterTopHlMode         = unibi_enter_top_hl_mode,
        EnterVerticalHlMode    = unibi_enter_vertical_hl_mode,
        SetAAttributes         = unibi_set_a_attributes,
        SetPgLenInch           = unibi_set_pglen_inch,
        TermcapInit2           = unibi_termcap_init2,
        TermcapReset           = unibi_termcap_reset,
        LinefeedIfNotLf        = unibi_linefeed_if_not_lf,
        BackspaceIfNotBs       = unibi_backspace_if_not_bs,
        OtherNonFunction_keys  = unibi_other_non_function_keys,
        ArrowKeyMap            = unibi_arrow_key_map,
        AcsULCorner            = unibi_acs_ulcorner,
        AcsLLCorner            = unibi_acs_llcorner,
        AcsURCorner            = unibi_acs_urcorner,
        AcsLRCorner            = unibi_acs_lrcorner,
        AcsLTee                = unibi_acs_ltee,
        AcsRTee                = unibi_acs_rtee,
        AcsBTee                = unibi_acs_btee,
        AcsTTee                = unibi_acs_ttee,
        AcsHLine               = unibi_acs_hline,
        AcsVLine               = unibi_acs_vline,
        AcsPlus                = unibi_acs_plus,
        MemoryLock             = unibi_memory_lock,
        MemoryUnlock           = unibi_memory_unlock,
        BoxChars1              = unibi_box_chars_1,
    };

    using SequenceContext = unibi_term;

    class Sequence
    {
      public:
        static Sequence CreateFromEnv()
        {
            return Sequence(unibi_from_env());
        }

      private:
        Sequence(SequenceContext* context)
        {
            _context = context;
        }

      public:
        ~Sequence()
        {
            unibi_destroy(_context);
        }

        bool Get(SequenceBoolean key) const
        {
            return unibi_get_bool(_context, static_cast<unibi_boolean>(key));
        }

        int Get(SequenceInteger key) const
        {
            return unibi_get_num(_context, static_cast<unibi_numeric>(key));
        }

        String Get(SequenceString key) const
        {
            return unibi_get_str(_context, static_cast<unibi_string>(key));
        }

        String CreateCursorMover(const Vector2 position) const
        {
            return "\x1B[" + std::to_string(position.y) + ';' + std::to_string(position.x) + 'H';
        }

      private:
        unibi_term* _context = nullptr;
    };
}

